#!/bin/bash

export BAGEL_NUM_THREADS=1
export OMP_NUM_THREADS=1

ibead=$1
natom=$2
QMnatom=$3
tocalc=$4
nstate=$5

MMnatom=$( echo "$natom-$QMnatom" | bc )
#head of thje file and basis set
cat > bagel.json << EOF
{ "bagel" : [
  {
  "title" : "molecule",
  "basis" : "svp",
  "df_basis" : "svp-jkfit",
  "angstrom" : "true",
  "geometry" : [
EOF

#head -n $QMnatom ../geom.dat.$ibead | awk '{print "    { \"atom\" : ""\""$1"\",  \"xyz\" : [  " $2",  "  $3",  "  $4 "]},"}' >> bagel.json #format he geometry from a file
#tail -n+2 pointcharges.xyz | awk '{print "    { \"atom\" : ""\"Q\",  \"xyz\" : [  " $2",  "  $3",  "  $4 "], \"charge\" : " $1 "},"}' >> bagel.json #add the point charge
# Format the geometry from the file with standard decimal notation
head -n $QMnatom ../geom.dat.$ibead | awk '{
    printf "    { \"atom\" : \"%s\",  \"xyz\" : [  %.8f,  %.8f,  %.8f ] },\n", $1, $2, $3, $4
}' >> bagel.json

# Add the point charges with reformatted numbers
tail -n+2 pointcharges.xyz | awk '{
    printf "    { \"atom\" : \"Q\",  \"xyz\" : [  %.8f,  %.8f,  %.8f ], \"charge\" : %.8f },\n", $2, $3, $4, $1
}' >> bagel.json



sed -i '${s/,$//}' bagel.json #remove the very last comma

cat >> bagel.json << EOF
  ]
},
EOF

if [[ -f "orbitals.archive" ]]; then
    # Load orbitals if the archive file exists
cat >> bagel.json << EOF
  {
    "title" : "load_ref",
    "file" : "orbitals",
    "continue_geom" : false
  },
EOF
else
cat >> bagel.json << EOF
  {
    "title" : "rohf"
  },
EOF
fi


#specification of the CASSCF
cat >> bagel.json << EOF
  {
    "title" : "forces",
    "export" : true,
    "grads" : [
      {
        "title": "force",
        "target": $(echo "$tocalc-1" | bc)
      }
    ],
    "method": [{
      "title": "casscf",
      "nspin": 0,
      "charge": 0,
      "nstate": 5,
      "nact": 6,
      "nclosed": 45,
      "thresh": 1.0e-8,
      "maxiter": 250
      }]
  },
  {
    "title": "save_ref",
    "file": "orbitals"
  }
]}
EOF


/home/srsen/bin/anaconda3/bin/mpirun -np 1 BAGEL bagel.json > bagel.out


cat > orca1.engrad << EOF
#
# Number of atoms
#
EOF
echo " $QMnatom" >> orca1.engrad
cat >> orca1.engrad << EOF
#
# The current total energy in Eh
#
EOF
head -1 ENERGY.out  >> orca1.engrad
cat >> orca1.engrad << EOF
#
# The current gradient in Eh/bohr
#
EOF
head -n $( echo "$QMnatom+1" | bc ) FORCE*.out | tail -$QMnatom | awk '{ print $2 "\n" $3 "\n" $4 }' >> orca1.engrad

echo $MMnatom > orca1.pcgrad
tail -$MMnatom FORCE*.out | awk '{ printf("  %15.12f  %15.12f  %15.12f\n", $2, $3, $4) }' >> orca1.pcgrad

touch orca1.gbw
#cp /home/postulka/CHEMSHELL/BAGEL_INTERFACE/ORCA_GRAD/CHEMSH/orca1.pcgrad .
#cp /home/postulka/CHEMSHELL/BAGEL_INTERFACE//ORCA_GRAD/CHEMSH/orca1.engrad .
