#!/bin/bash

ibead=$1
natom=$2
QMnatom=$3

#head of thje file and basis set
cat > bagel.json << EOF
{ "bagel" : [
    
{   
  "title" : "molecule",
  "basis" : "aug-cc-pcvdz",
  "df_basis" : "cc-pvdz-jkfit",
  "angstrom" : "true",
  "geometry" : [
EOF

head -n $QMnatom geom.dat.$ibead | awk '{print "    { \"atom\" : ""\""$1"\",  \"xyz\" : [  " $2",  "  $3",  "  $4 "]},"}' >> bagel.json #format he geometry from a file
tail -n+2 CHEMSH/pointcharges.xyz | awk '{print "    { \"atom\" : ""\"Q\",  \"xyz\" : [  " $2",  "  $3",  "  $4 "], \"charge\" : " $1 "},"}' >> bagel.json #add the point charge
sed -i '${s/,$//}' bagel.json #remove the very last comma

#specification of the CASSCF
cat >> bagel.json << EOF
  ]
},

{
  "title" : "forces",
  "export" : true,
  "grads" : [
  { "title" : "force", "target" : 0 }
  ],
  "method" : [ {
      "title" : "casscf",
      "nact" : 4,
      "nclosed" : 6,
      "nstate" : 4,
      "maxiter": 250
   } ]
}
]}
EOF

